import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowDown, ArrowLeft, ArrowRight, Check, CircleHelp, Contrast, Expand, Focus, Gauge, Layers3, Moon, RotateCcw, Sun, X } from 'lucide-react'
import { colorAtHue, colorScale, contrastRatio, hexToHsl, hexToRgb, hslToHex } from './utils/color'

const totalSlides = 20
const slideTitles = ['Color in UI Design', 'Color communicates', 'Color has three dimensions', 'The color wheel', 'Relationships create palettes', 'From color to UI palette', 'Roles, not just values', 'Colors have meaning', 'Color creates hierarchy', 'The 60–30–10 rule', 'Contrast = legibility', 'Never color alone', 'Dark mode is a system', 'From design to code', 'One hue, many jobs', 'Color mistakes', 'Live demo: fix the UI', 'A system changes everything', 'The developer pipeline', 'Before you ship']
const spring = { type: 'spring' as const, stiffness: 150, damping: 22 }

function Kicker({ children }: { children: React.ReactNode }) {
  return <div className="kicker"><span />{children}</div>
}

function SlideHeading({ eyebrow, title, accent }: { eyebrow: string; title: React.ReactNode; accent?: React.ReactNode }) {
  return <header className="slide-heading"><Kicker>{eyebrow}</Kicker><h1>{title}{accent && <span className="heading-accent"> {accent}</span>}</h1></header>
}

function ProductMock({ variant = 'good', highlight = '', dark = false }: { variant?: 'good' | 'bad'; highlight?: string; dark?: boolean }) {
  return <div className={`product-mock ${variant === 'bad' ? 'mock-bad' : ''} ${dark ? 'mock-dark' : ''}`}>
    <aside className="mock-sidebar"><div className="mock-brand"><span className="brand-dot" />Northstar</div><span className="mock-nav active">◈ <b>Overview</b></span><span className="mock-nav">◷ <b>Activity</b></span><span className="mock-nav">▦ <b>Projects</b></span><span className="mock-nav">⚙ <b>Settings</b></span><div className="mock-user"><span>AM</span><div><b>Alex Morgan</b><small>Pro workspace</small></div></div></aside>
    <main className="mock-main"><div className="mock-top"><div><small>MONDAY, OCTOBER 21</small><b>Good morning, Alex <span>✳</span></b></div><button className={`mock-cta ${highlight === 'primary' ? 'is-highlighted' : ''}`}>+ New project</button></div>
      <div className="mock-metrics">{[['Total revenue', '$48,290', '+12.8%'], ['Active users', '2,841', '+8.2%'], ['Conversion', '4.62%', '+0.6%']].map(([title, number, delta]) => <div className={`metric ${highlight === 'surface' ? 'is-highlighted' : ''}`} key={title}><small>{title}</small><strong>{number}</strong><span>↗ {delta}</span></div>)}</div>
      <div className="mock-chart"><div className="chart-head"><b>Performance</b><button>Last 30 days⌄</button></div><div className="chart-bars">{[38, 54, 44, 68, 59, 78, 54, 88, 72, 94, 70, 84, 62, 92, 74, 100, 69, 87, 58, 80, 67, 96, 75, 88].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div><div className="chart-axis"><span>Oct 01</span><span>Oct 10</span><span>Oct 21</span></div></div>
      <div className="mock-activity"><div className="chart-head"><b>Recent activity</b><a>View all <ArrowRight size={12} /></a></div>{[['AP', 'A new report is ready', '2 min ago'], ['JD', 'Jamie joined the workspace', '1 hr ago']].map(([initials, title, time]) => <div className="activity-row" key={initials}><span>{initials}</span><b>{title}</b><small>{time}</small></div>)}</div>
    </main>
  </div>
}

const harmonies = [
  { name: 'Complementary', offsets: [0, 180], points: [0, 180] },
  { name: 'Split complementary', offsets: [0, 150, 210], points: [0, 150, 210] },
  { name: 'Analogous', offsets: [-30, 0, 30], points: [-30, 0, 30] },
  { name: 'Triadic', offsets: [0, 120, 240], points: [0, 120, 240] },
  { name: 'Tetradic', offsets: [0, 60, 180, 240], points: [0, 60, 180, 240] },
  { name: 'Square', offsets: [45, 135, 225, 315], points: [45, 135, 225, 315] },
] as const

function RelationshipDemo() {
  const [mode, setMode] = useState<(typeof harmonies)[number]['name']>('Complementary')
  const [hue, setHue] = useState(158)
  const selectedHarmony = harmonies.find((harmony) => harmony.name === mode) ?? harmonies[0]
  const colors = selectedHarmony.offsets.map((offset) => hslToHex({ h: (hue + offset + 360) % 360, s: 70, l: 56 }))
  const examples: Record<(typeof harmonies)[number]['name'], { ui: string; reference: string }> = {
    Complementary: { ui: 'Analytics UI: keep charts teal; reserve warm coral for the “Create report” CTA.', reference: 'IKEA’s blue and yellow logo is a familiar near-complementary pairing. Van Gogh’s Cafe Terrace at Night sets golden lights against deep blue.' },
    'Split complementary': { ui: 'Product UI: use blue for the primary action, with orange and red-orange for supporting chart series.', reference: 'This is easier to spot in a designed palette than a famous logo; it gives one base hue two contrasting, less-opposite partners.' },
    Analogous: { ui: 'Revenue UI: use neighboring blue-green shades for related chart series.', reference: 'Van Gogh’s Almond Blossom uses a family of neighboring cool blues around the branches and sky.' },
    Triadic: { ui: 'Project UI: distinguish three categories; label each, don’t imply status.', reference: 'Piet Mondrian’s Broadway Boogie Woogie is built around a vivid red, yellow, and blue triad.' },
    Tetradic: { ui: 'Operations UI: map four distinct data series to four labeled hues.', reference: 'Microsoft’s four-color window mark is a loose example of two warm/cool complementary pairs.' },
    Square: { ui: 'Multi-section UI: give four feature areas distinct hues, with neutral UI around them.', reference: 'Google’s four-color G mark loosely suggests a square harmony; its brand hues are not an exact geometric match.' },
  }
  const points = selectedHarmony.points.map((offset, index) => {
    const angle = (hue + offset - 90) * Math.PI / 180
    return { x: 50 + 39 * Math.cos(angle), y: 50 + 39 * Math.sin(angle), color: colors[index] }
  })
  const pointString = points.map(({ x, y }) => `${x},${y}`).join(' ')
  return <div className="relationship-demo"><div className="harmony-options" role="group" aria-label="Choose a color harmony">{harmonies.map((harmony) => {
    const miniColors = harmony.offsets.map((offset) => hslToHex({ h: (hue + offset + 360) % 360, s: 75, l: 55 }))
    const miniPoints = harmony.points.map((offset) => {
      const angle = (hue + offset - 90) * Math.PI / 180
      return `${50 + 36 * Math.cos(angle)},${50 + 36 * Math.sin(angle)}`
    })
    return <button key={harmony.name} className={`harmony-option ${mode === harmony.name ? 'selected' : ''}`} aria-pressed={mode === harmony.name} onClick={() => setMode(harmony.name)}><span className="harmony-wheel"><i/><svg viewBox="0 0 100 100" aria-hidden="true"><polygon points={miniPoints.join(' ')} />{miniPoints.map((point, index) => <circle key={point} cx={point.split(',')[0]} cy={point.split(',')[1]} r="3.1" fill={miniColors[index]} />)}</svg></span><b>{harmony.name}</b></button>
  })}</div><label className="inline-control">Base hue <input aria-label="Base hue" type="range" min="0" max="359" value={hue} onChange={(event) => setHue(Number(event.target.value))} /></label><div className="harmony-result"><div className="harmony-wheel harmony-wheel-large"><i/><svg viewBox="0 0 100 100" role="img" aria-label={`${mode} color wheel relationship`}><polygon points={pointString} />{points.map(({ x, y, color }) => <circle key={`${x}-${y}`} cx={x} cy={y} r="3.7" fill={color} />)}</svg></div><div className="relationship-swatches">{colors.map((color, index) => <motion.div layout key={`${mode}-${index}`} title={color.toUpperCase()} style={{ backgroundColor: color }}><small>{color.toUpperCase()}</small></motion.div>)}</div></div><div className="relationship-note"><b>{mode}</b><span>{mode === 'Complementary' ? 'Opposite hues create a focused accent.' : mode === 'Analogous' ? 'Neighboring hues create a cohesive range.' : mode === 'Split complementary' ? 'One hue plus its two near-opposites.' : mode === 'Triadic' ? 'Three evenly spaced hues.' : mode === 'Tetradic' ? 'Two complementary pairs.' : 'Four evenly spaced hues.'}</span></div><div className="relationship-usecase"><div><small>UI EXAMPLE</small><p>{examples[mode].ui}</p></div><div><small>REAL-WORLD REFERENCE</small><p>{examples[mode].reference}</p></div><em>Brand and artwork examples are visual approximations, not claims about the creator’s original method.</em></div></div>
}

function ColorWheel() {
  const [hue, setHue] = useState(158)
  const center = 140
  const polar = (radius: number, angle: number) => ({ x: center + radius * Math.cos((angle - 90) * Math.PI / 180), y: center + radius * Math.sin((angle - 90) * Math.PI / 180) })
  const segments = Array.from({ length: 36 }, (_, index) => {
    const start = index * 10
    const end = start + 10
    const outerStart = polar(124, start)
    const outerEnd = polar(124, end)
    const innerEnd = polar(70, end)
    const innerStart = polar(70, start)
    return { hue: index * 10, d: `M ${outerStart.x} ${outerStart.y} A 124 124 0 0 1 ${outerEnd.x} ${outerEnd.y} L ${innerEnd.x} ${innerEnd.y} A 70 70 0 0 0 ${innerStart.x} ${innerStart.y} Z` }
  })
  const selected = hslToHex({ h: hue, s: 78, l: 56 })
  const rgb = hexToRgb(selected)
  const hsl = hexToHsl(selected)
  return <div className="wheel-layout"><div className="wheel-wrap"><svg viewBox="0 0 280 280" role="img" aria-label="Interactive color wheel">{segments.map((segment) => <path key={segment.hue} d={segment.d} fill={`hsl(${segment.hue} 82% 56%)`} stroke="#171c19" strokeWidth="1" onClick={() => setHue(segment.hue + 5)} className="wheel-segment" />)}<circle cx="140" cy="140" r="62" fill="#171c19"/><circle cx="140" cy="140" r="48" fill={selected} className="wheel-center"/><circle cx={polar(98, hue).x} cy={polar(98, hue).y} r="7" fill="white" stroke="#111412" strokeWidth="3" /></svg></div><div className="wheel-detail"><Kicker>Selected color</Kicker><h3>{selected.toUpperCase()}</h3><div className="value-grid"><div><small>RGB</small><b>{rgb.r}, {rgb.g}, {rgb.b}</b></div><div><small>HSL</small><b>{hsl.h}°, {hsl.s}%, {hsl.l}%</b></div></div><div className="mini-swatches"><span style={{ background: colorAtHue(selected, 180) }} /><span style={{ background: colorAtHue(selected, -30) }} /><span style={{ background: colorAtHue(selected, 30) }} /><span style={{ background: colorAtHue(selected, 120) }} /><small>Opposite · Neighbors · Triadic</small></div><label className="range-label">Hue <input aria-label="Selected wheel hue" type="range" min="0" max="359" value={hue} onChange={(event) => setHue(Number(event.target.value))} /></label></div></div>
}

function ContrastChecker() {
  const [foreground, setForeground] = useState('#5d6b65')
  const [background, setBackground] = useState('#ffffff')
  const ratio = contrastRatio(foreground, background)
  return <div className="contrast-demo"><div className="contrast-preview" style={{ color: foreground, backgroundColor: background }}><small>LIVE PREVIEW</small><strong>Readable by design.</strong><span>Body text at a comfortable size.</span></div><div className="contrast-controls"><label>Foreground <input type="color" value={foreground} onChange={(event) => setForeground(event.target.value)} /></label><label>Background <input type="color" value={background} onChange={(event) => setBackground(event.target.value)} /></label><div className="ratio-number"><small>Contrast ratio</small><strong>{ratio.toFixed(2)} <span>: 1</span></strong></div><div className="wcag-row"><span>AA normal text <b className={ratio >= 4.5 ? 'pass' : 'fail'}>{ratio >= 4.5 ? 'PASS' : 'FAIL'}</b></span><span>AAA normal text <b className={ratio >= 7 ? 'pass' : 'fail'}>{ratio >= 7 ? 'PASS' : 'FAIL'}</b></span></div></div></div>
}

function TokenDemo() {
  const [primary, setPrimary] = useState('#78d5ad')
  return <div className="token-demo"><div className="token-list">{[['Primary', primary], ['Secondary', '#7798e8'], ['Background', '#f7f8f5'], ['Surface', '#ffffff'], ['Text', '#202923'], ['Muted', '#77827a'], ['Border', '#dce3dd'], ['Success', '#31835a'], ['Warning', '#ae7618'], ['Error', '#bb5550'], ['Info', '#527dbe']].map(([name, color]) => <div className="token-row" key={name}><i style={{ backgroundColor: color }} /><span>{name}</span><code>{color}</code>{name === 'Primary' && <input aria-label="Change primary token" type="color" value={primary} onChange={(event) => setPrimary(event.target.value)} />}</div>)}</div><div className="token-preview" style={{ '--token-primary': primary } as React.CSSProperties}><div className="token-preview-top"><span>◈</span><small>FIELDNOTE / 01</small><span>···</span></div><div className="token-preview-content"><small>YOUR WORKSPACE</small><h3>Ship work that matters.</h3><p>A calm place to move your team forward.</p><button>Open workspace <ArrowRight size={14} /></button></div><div className="token-preview-foot"><span><i /> All systems operational</span><small>Updated just now</small></div></div></div>
}

function BadUiDemo() {
  const [step, setStep] = useState(0)
  const steps = ['Define the palette', 'Establish hierarchy', 'Add semantic colors', 'Fix contrast', 'Apply consistent tokens', 'Add dark mode']
  return <div className={`repair-demo ${step >= 6 ? 'repair-dark' : ''}`}><div className={`repair-screen repair-step-${step}`}><header><span>☀️ <b>Sunshine Analytics!!!</b></span><button>✨ Export ✨</button><button>Delete</button><button>BUY NOW</button></header><div className="repair-welcome"><span>⚠︎ Revenue is down!!!</span><h3>Dashboard</h3><strong>$48,290</strong><button>+ Add</button></div><div className="repair-grid"><div><small>Total sales</small><b>$12,409</b><i>+12%</i></div><div><small>Users online</small><b>2,804</b><i>ERROR!!</i></div><div><small>Conversion</small><b>4.8%</b><i>Warning</i></div></div><div className="repair-bars">{[20, 55, 37, 78, 43, 90, 58, 70, 42, 94, 63, 83].map((height, index) => <i style={{ height: `${height}%` }} key={index} />)}</div><footer>Success!  •  ERROR!  •  Warning!!!  •  💥</footer></div><div className="repair-controls"><div><Kicker>Live refactor · Step {Math.min(step, 6)} / 6</Kicker><h3>{step === 0 ? 'A little too loud?' : step >= 6 ? 'Now it feels intentional.' : steps[step - 1]}</h3><p>{step === 0 ? 'We’ll refactor the interface one decision at a time.' : step >= 6 ? 'Roles, rhythm, and contrast. Same data, a clearer story.' : ['Choose one accent, then let neutrals do the heavy lifting.', 'Make the main action obvious. Demote the rest.', 'Keep success, warning, and error meanings stable.', 'Raise text contrast without adding visual noise.', 'Replace one-off values with reusable roles.', 'Build a surface and text hierarchy for low light.'][step - 1]}</p></div><div className="repair-action"><div className="repair-dots">{steps.map((_, index) => <span className={step > index ? 'done' : ''} key={index} />)}</div><button className="button-primary" onClick={() => setStep(step >= 6 ? 0 : step + 1)}>{step === 0 ? 'Fix this UI' : step >= 6 ? 'Reset demo' : 'Next step'} <ArrowRight size={15} /></button></div></div></div>
}

function SlideContent({ index }: { index: number }) {
  const [hsl, setHsl] = useState({ h: 158, s: 55, l: 58 })
  const [selectedRole, setSelectedRole] = useState('Primary')
  const [hierarchyGood, setHierarchyGood] = useState(false)
  const [accentShare, setAccentShare] = useState(10)
  const [darkMode, setDarkMode] = useState(false)
  const [activeMistake, setActiveMistake] = useState(0)
  const [checks, setChecks] = useState<boolean[]>(Array(8).fill(false))
  const selectedColor = hslToHex(hsl)
  const semantic = [['Success', 'Payment successful', '✓', '#8bd0a5'], ['Error', 'Invalid password', '×', '#e37b72'], ['Warning', 'Storage almost full', '!', '#edbf68'], ['Information', 'New update available', 'i', '#82a9e9']]
  const checklist = ['Does every color have a purpose?', 'Is the hierarchy clear?', 'Are semantic colors consistent?', 'Is contrast sufficient?', 'Does the UI work for color-blind users?', 'Is information communicated without color alone?', 'Does dark mode have proper hierarchy?', 'Are colors defined as reusable tokens?']

  switch (index) {
    case 0: return <div className="title-layout"><div className="title-copy"><Kicker>Frontend fieldnotes <span className="edition">VOL. 04 · 2025</span></Kicker><h1>Color in<br /><em>UI Design</em></h1><p>Choosing colors is easy.<br /><span>Using them well is the hard part.</span></p><div className="title-tags"><span><Contrast size={14} /> Systems</span><span><Layers3 size={14} /> Interfaces</span><span><Gauge size={14} /> Accessibility</span></div></div><div className="spectrum-art" aria-label="Animated color spectrum"><div className="spectrum-ring ring-one"/><div className="spectrum-ring ring-two"/><div className="spectrum-orbit"><i/><i/><i/><i/><i/><i/></div><div className="spectrum-core">COLOR<br /><small>WITH INTENT</small></div><span className="orbit-label label-a">H 158°</span><span className="orbit-label label-b">#78D5AD</span><span className="orbit-label label-c">01 / 20</span></div></div>
    case 1: return <><SlideHeading eyebrow="01 / The why" title={<>Color isn't decoration.<br /><span className="heading-accent">Color communicates.</span></>} /><div className="compare-layout"><div className="compare-side"><Kicker>Without a system</Kicker><div className="poor-ui"><header><b>Acme analytics</b><button>Home</button><button style={{ background: '#ff793a' }}>Reports</button><button style={{ background: '#6c4dda' }}>Settings</button></header><h3>Good morning!!!</h3><div><b style={{ color: '#ff2525' }}>$24,928 <small>+3%</small></b><button style={{ background: '#f1d233', color: '#76550a' }}>Click here</button></div><p style={{ color: '#bdbdbd' }}>Everything you need to know is right here.</p></div></div><motion.div className="transform-arrow" animate={{ x: [0, 5, 0] }} transition={{ repeat: Infinity, duration: 2 }}><ArrowRight /></motion.div><div className="compare-side"><Kicker>With intention</Kicker><ProductMock /></div></div></>
    case 2: return <><SlideHeading eyebrow="02 / Color theory" title={<>Color has <span className="heading-accent">three dimensions.</span></>} /><div className="theory-layout"><div className="theory-controls"><div className="theory-slider"><label>Hue <small>{hsl.h}°</small></label><input aria-label="Hue" type="range" min="0" max="359" value={hsl.h} onChange={(event) => setHsl({ ...hsl, h: Number(event.target.value) })} /><small className="range-caption"><span>0°</span><span>360°</span></small></div><div className="theory-slider"><label>Saturation <small>{hsl.s}%</small></label><input aria-label="Saturation" type="range" min="0" max="100" value={hsl.s} onChange={(event) => setHsl({ ...hsl, s: Number(event.target.value) })} /><small className="range-caption"><span>Muted</span><span>Vivid</span></small></div><div className="theory-slider"><label>Lightness <small>{hsl.l}%</small></label><input aria-label="Lightness" type="range" min="5" max="95" value={hsl.l} onChange={(event) => setHsl({ ...hsl, l: Number(event.target.value) })} /><small className="range-caption"><span>Dark</span><span>Light</span></small></div><code>hsl({hsl.h}, {hsl.s}%, {hsl.l}%)</code></div><motion.div className="hsl-preview" animate={{ backgroundColor: selectedColor }} transition={{ duration: .25 }}><span className="preview-hue">HUE</span><div className="preview-caption"><b>{selectedColor.toUpperCase()}</b><small>Move the controls.<br />Watch the color change.</small></div><span className="preview-glow" /></motion.div><div className="theory-legend">{[['01', 'Hue', 'Which color family?'], ['02', 'Saturation', 'How vivid or muted?'], ['03', 'Lightness', 'How bright or deep?']].map(([n, title, text]) => <div key={n}><small>{n}</small><b>{title}</b><span>{text}</span></div>)}</div></div></>
    case 3: return <><SlideHeading eyebrow="03 / Color theory" title={<>Start with a hue.<br /><span className="heading-accent">Explore the wheel.</span></>} /><ColorWheel /></>
    case 4: return <><SlideHeading eyebrow="04 / Color theory" title={<>Relationships create <span className="heading-accent">palettes.</span></>} /><div className="relationship-layout"><div className="relationship-intro"><span className="large-index">04</span><h3>One base.<br />Different energy.</h3><p>Use the wheel when starting a palette or choosing chart colors. Then assign roles and check contrast; harmony alone doesn’t make a usable UI.</p><div className="relationship-key"><span><i style={{ background: '#78d5ad' }} /> Base hue</span><span><i style={{ background: '#7798e8' }} /> Supporting hues</span></div></div><RelationshipDemo /></div></>
    case 5: return <><SlideHeading eyebrow="05 / Product thinking" title={<>A UI needs roles,<br /><span className="heading-accent">not just “blue.”</span></>} /><TokenDemo /></>
    case 6: return <><SlideHeading eyebrow="06 / Product thinking" title={<>Roles, <span className="heading-accent">not just values.</span></>} /><div className="roles-layout"><div className="roles-selector">{[['Primary', '#78d5ad', 'Main action'], ['Secondary', '#7798e8', 'Supporting action'], ['Accent', '#edbf68', 'Highlight'], ['Neutral', '#b7c0ba', 'Structure']].map(([role, color, description]) => <button className={selectedRole === role ? 'role-selected' : ''} onClick={() => setSelectedRole(role)} key={role}><i style={{ background: color }} /><b>{role}</b><span>{description}</span><ArrowRight size={15} /></button>)}</div><div className="role-product"><ProductMock highlight={selectedRole.toLowerCase() === 'neutral' ? 'surface' : selectedRole.toLowerCase()} /><div className="role-caption"><span className="live-dot" /> Highlighting: <b>{selectedRole}</b><span>Color is a product decision.</span></div></div></div></>
    case 7: return <><SlideHeading eyebrow="07 / Product thinking" title={<>Colors have <span className="heading-accent">meaning.</span></>} /><div className="semantic-layout"><div className="semantic-grid">{semantic.map(([name, message, icon, color], index) => <motion.button whileHover={{ y: -4 }} transition={spring} className="semantic-card" style={{ '--semantic': color } as React.CSSProperties} key={name}><div className="semantic-icon">{icon}</div><small>0{index + 1} / {name}</small><h3>{message}</h3><span>Just now <i /></span></motion.button>)}</div><div className="semantic-caption"><span>✓</span><p>Semantic colors communicate meaning consistently across the product. Not just because they “look nice.”</p></div></div></>
    case 8: return <><SlideHeading eyebrow="08 / Product thinking" title={<>If everything is colorful,<br /><span className="heading-accent">nothing is important.</span></>} /><div className="hierarchy-layout"><div className="hierarchy-toggle"><span>{hierarchyGood ? 'After · Intentional hierarchy' : 'Before · Everything shouts'}</span><button className="text-control" onClick={() => setHierarchyGood(!hierarchyGood)}><RotateCcw size={14} /> Toggle view</button></div><div className={`hierarchy-demo ${hierarchyGood ? 'hierarchy-good' : 'hierarchy-bad'}`}><div className="hierarchy-info"><small>PROJECT ATLAS · UPDATED 2H AGO</small><h3>Quarterly<br />performance</h3><p>Your team's impact, at a glance.</p><div className="hierarchy-number">$128,420 <span>↗ 18.4%</span></div></div><div className="hierarchy-actions"><button className="main-action">View report <ArrowRight size={15} /></button><button className="second-action">Share report</button><p>Last updated by <b>Alex Morgan</b><br /><span>All changes saved · yesterday</span></p><button className="disabled-action" disabled>Archive report</button></div></div><div className="hierarchy-note"><span className="hierarchy-line"/><p>Color gives the primary action a clear lane. Everything else gets out of the way.</p></div></div></>
    case 9: return <><SlideHeading eyebrow="09 / Proportion" title={<>The <span className="heading-accent">60–30–10</span> rule.</>} /><div className="proportion-layout"><div className="proportion-copy"><div><strong>60<span>%</span></strong><p>Dominant<br /><small>Background + structure</small></p></div><div><strong>30<span>%</span></strong><p>Secondary<br /><small>Surfaces + supporting UI</small></p></div><div><strong>10<span>%</span></strong><p>Accent<br /><small>Actions + focus</small></p></div><label className="accent-range">Accent share <b>{accentShare}%</b><input type="range" min="10" max="40" step="5" value={accentShare} onChange={(event) => setAccentShare(Number(event.target.value))} /></label></div><div className="proportion-preview" style={{ '--noise': `${accentShare * 2.5}%` } as React.CSSProperties}><div className="proportion-app"><div><span className="brand-dot" /> northstar</div><h3>Good work<br />starts with focus.</h3><p>One clear action beats a dozen bright ones.</p><button>Start a project <ArrowRight size={14} /></button><div className="proportion-footer"><i/><i/><i/><i/><i/><i/><i/><i/></div></div><div className="proportion-status"><span>{accentShare <= 15 ? '✓ Focused' : '⚠ Getting noisy'}</span><small>{accentShare}% accent surface</small></div></div></div></>
    case 10: return <><SlideHeading eyebrow="10 / Accessibility" title={<>Contrast = <span className="heading-accent">legibility.</span></>} /><div className="contrast-layout"><div className="contrast-context"><p>Contrast isn’t just an aesthetic choice. It decides who can read, act, and understand.</p><div className="contrast-stats"><div><b>4.5:1</b><small>AA · body text</small></div><div><b>7:1</b><small>AAA · body text</small></div></div><span className="contrast-standard">WCAG 2.2 · AA</span></div><ContrastChecker /></div></>
    case 11: return <><SlideHeading eyebrow="11 / Accessibility" title={<>Never communicate<br /><span className="heading-accent">important information with color alone.</span></>} /><div className="access-layout"><div className="access-examples"><div className="access-problem"><small>01 / COLOR VISION</small><div><span className="red-dot"/> <span className="green-dot"/></div><p>Red and green can look nearly identical.</p></div><div className="access-problem"><small>02 / ERROR STATE</small><div className="error-example"><b>●</b><strong>Error</strong><span>Invalid email address</span></div><p>Pair color with an icon and a clear label.</p></div><div className="access-problem"><small>03 / CONTRAST</small><div className="contrast-compare"><span>❌ Poor contrast</span><b>✅ Better contrast</b></div><p>Check the actual text and its surface.</p></div></div><div className="access-takeaway"><div className="access-mark">Aa</div><Kicker>Design for more people</Kicker><h3>Color should<br />reinforce the signal.<br /><em>Never be the signal.</em></h3><span>Icon · label · pattern · text</span></div></div></>
    case 12: return <><SlideHeading eyebrow="12 / Color modes" title={<>Dark mode is a <span className="heading-accent">system.</span></>} /><div className="darkmode-layout"><div className="darkmode-copy"><p>Don’t invert white and black. Rebuild the hierarchy.</p><ul>{['Background', 'Surface', 'Text hierarchy', 'Borders + shadows', 'Semantic colors', 'Saturation'].map((item) => <li key={item}><Check size={15} /> {item}</li>)}</ul><button className="mode-toggle" onClick={() => setDarkMode(!darkMode)}>{darkMode ? <Moon size={16} /> : <Sun size={16} />} <span>{darkMode ? 'Dark mode' : 'Light mode'}</span><i className={darkMode ? 'toggle-on' : ''} /></button></div><motion.div className="darkmode-product" animate={{ backgroundColor: darkMode ? '#1e2621' : '#f4f6f2', color: darkMode ? '#e8efe9' : '#26332b' }} transition={{ duration: .35 }}><ProductMock dark={darkMode} /><div className="mode-note"><span>{darkMode ? 'NIGHT SHIFT' : 'DAYLIGHT'}</span><b>{darkMode ? 'Low-glare surfaces. Same clear signals.' : 'A soft neutral canvas. Calm, not clinical.'}</b></div></motion.div></div></>
    case 13: return <><SlideHeading eyebrow="13 / Frontend systems" title={<>From design decision<br /><span className="heading-accent">to component API.</span></>} /><div className="pipeline"><div className="pipeline-flow">{[['Design', '◈'], ['Tokens', '▤'], ['CSS vars', '⌘'], ['Components', '◫'], ['Application', '▦']].map(([name, icon], index) => <div className="pipeline-step" key={name}><div><span>{icon}</span><b>{name}</b></div>{index < 4 && <ArrowRight size={16} />}</div>)}</div><div className="code-preview"><div className="code-title"><span><i/> variables.css</span><small>DESIGN TOKENS → RUNTIME</small></div><pre><code><span className="syntax-selector">:root</span> {'{'}<br />  <span className="syntax-prop">--color-primary</span>: <span className="syntax-value">#78d5ad</span>;<br />  <span className="syntax-prop">--color-primary-hover</span>: <span className="syntax-value">#58b78f</span>;<br />  <span className="syntax-prop">--color-background</span>: <span className="syntax-value">#f7f8f5</span>;<br />  <span className="syntax-prop">--color-surface</span>: <span className="syntax-value">#ffffff</span>;<br />  <span className="syntax-prop">--color-text</span>: <span className="syntax-value">#202923</span>;<br />  <span className="syntax-prop">--color-border</span>: <span className="syntax-value">#dce3dd</span>;<br />  <span className="syntax-prop">--color-success</span>: <span className="syntax-value">#31835a</span>;<br />  <span className="syntax-prop">--color-error</span>: <span className="syntax-value">#bb5550</span>;<br />{'}'}</code></pre><span className="token-benefit"><Check size={13}/> Change once. Update the product everywhere.</span></div></div></>
    case 14: return <><SlideHeading eyebrow="14 / Frontend systems" title={<>One hue.<br /><span className="heading-accent">Eleven useful values.</span></>} /><div className="scale-layout"><div className="scale-label"><Kicker>Tailwind + design systems</Kicker><h3>From a single<br />primary hue.</h3><p>Light surfaces, readable text, hover states, focus rings, and more. All from one source.</p><div className="scale-code"><code>primary-50</code><code>primary-100</code><code>primary-500</code><code>primary-600</code><code>primary-900</code></div></div><ColorScale hueColor={selectedColor}/></div></>
    case 15: return <><SlideHeading eyebrow="15 / Anti-patterns" title={<>Color mistakes<br /><span className="heading-accent">you can spot in a second.</span></>} /><div className="mistakes-layout"><div className="mistakes-list">{['Too many colors', 'Poor contrast', 'Random semantics', 'No hierarchy', 'Color everywhere', 'Red / green only', 'Inconsistent shades', 'Pure black + white'].map((mistake, index) => <button key={mistake} className={activeMistake === index ? 'mistake-active' : ''} onClick={() => setActiveMistake(index)}><span>0{index + 1}</span>{mistake}<ArrowRight size={14}/></button>)}</div><div className={`mistake-display mistake-${activeMistake}`}><div className="mistake-window"><div className="mistake-windowbar"><i/><i/><i/><span>dashboard / design-system</span></div><ProductMock variant="bad"/></div><div className="mistake-caption"><span>ISSUE 0{activeMistake + 1}</span><b>{['Too many colors compete for attention.', 'Low contrast makes key data disappear.', 'Color labels contradict their meaning.', 'Every element claims priority.', 'Accent is no longer an accent.', 'Color vision differences hide the signal.', 'Near-miss shades feel unintentional.', 'Harsh extremes erase visual nuance.'][activeMistake]}</b></div></div></div></>
    case 16: return <><SlideHeading eyebrow="16 / Live refactor" title={<>Same product.<br /><span className="heading-accent">Better decisions.</span></>} /><BadUiDemo /></>
    case 17: return <><SlideHeading eyebrow="17 / Transformation" title={<>A system changes <span className="heading-accent">everything.</span></>} /><div className="before-after"><div className="before-after-panels"><div><Kicker>Before · Guesswork</Kicker><ProductMock variant="bad"/></div><div className="before-after-arrow"><ArrowRight size={22}/></div><div><Kicker>After · Intentional</Kicker><ProductMock/></div></div><div className="transformation-list">{[['Too many colors', 'Controlled palette'], ['Random meaning', 'Semantic colors'], ['Weak contrast', 'Accessible contrast'], ['Hardcoded values', 'Design tokens']].map(([from, to], index) => <div key={from}><span>0{index + 1}</span><s>{from}</s><ArrowRight size={13}/><b>{to}</b></div>)}</div></div></>
    case 18: return <><SlideHeading eyebrow="18 / Frontend practice" title={<>Turn color into a <span className="heading-accent">reusable API.</span></>} /><div className="developer-layout"><div className="developer-flow">{['COLOR THEORY', 'COLOR PALETTE', 'DESIGN TOKENS', 'CSS VARIABLES', 'COMPONENTS', 'APPLICATION'].map((label, index) => <div key={label}><span>0{index + 1}</span><b>{label}</b>{index < 5 && <ArrowDown size={14}/>}</div>)}</div><div className="component-code"><div className="code-title"><span><i/> Button.tsx</span><small>DESIGN SYSTEM</small></div><pre><code><span className="syntax-muted">// Meaning lives in the variant.</span><br /><span className="syntax-key">&lt;Button</span> <span className="syntax-prop">variant</span>=<span className="syntax-string">"primary"</span> /&gt;<br /><span className="syntax-key">&lt;Button</span> <span className="syntax-prop">variant</span>=<span className="syntax-string">"danger"</span> /&gt;<br /><span className="syntax-key">&lt;Alert</span> <span className="syntax-prop">variant</span>=<span className="syntax-string">"warning"</span> /&gt;<br /><span className="syntax-key">&lt;Badge</span> <span className="syntax-prop">variant</span>=<span className="syntax-string">"success"</span> /&gt;</code></pre><div className="component-samples"><button>Primary action <ArrowRight size={14}/></button><span>● Warning · Low storage</span><i>✓ Success</i></div><p>Good color systems become reusable through components.</p></div></div></>
    case 19: return <><SlideHeading eyebrow="19 / Ship with intent" title={<>Before you <span className="heading-accent">ship.</span></>} /><div className="checklist-layout"><div className="checklist-items">{checklist.map((item, index) => <button key={item} className={checks[index] ? 'checked' : ''} onClick={() => setChecks(checks.map((value, i) => i === index ? !value : value))}><span>{checks[index] && <Check size={13}/>}</span><b>{item}</b><small>0{index + 1}</small></button>)}</div><div className="final-statement"><Kicker>{checks.filter(Boolean).length} / 8 checks complete</Kicker><h2>Don't just<br />pick colors.</h2><p>Give them <em>meaning.</em></p><div className="final-mark">C<span>·</span></div></div></div></>
    default: return null
  }
}

function ColorScale({ hueColor }: { hueColor: string }) {
  const [baseColor, setBaseColor] = useState(hueColor)
  const scale = colorScale(baseColor)
  return <div className="scale-demo"><div className="scale-bar">{scale.map((color, index) => <div key={index} style={{ backgroundColor: color }}><span>{[50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950][index]}</span></div>)}</div><div className="scale-details">{scale.map((color, index) => <div key={index}><i style={{ backgroundColor: color }} /><small>{[50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950][index]}</small><code>{color.toUpperCase()}</code></div>)}</div><label className="scale-picker">Try another hue <input type="color" value={baseColor} aria-label="Set scale base color" onChange={(event) => setBaseColor(event.target.value)} /></label></div>
}

function KeyboardHelp({ onClose }: { onClose: () => void }) {
  return <motion.div className="help-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><motion.div className="help-dialog" initial={{ y: 10, scale: .98 }} animate={{ y: 0, scale: 1 }} onClick={(event) => event.stopPropagation()}><button className="help-close" onClick={onClose} aria-label="Close shortcuts"><X size={18}/></button><Kicker>Quick controls</Kicker><h2>Move around</h2>{[['← / →', 'Previous / next slide'], ['Space', 'Next slide'], ['Home / End', 'First / last slide'], ['F', 'Toggle fullscreen'], ['Esc', 'Exit fullscreen'], ['?', 'Show this panel']].map(([key, action]) => <div className="shortcut-row" key={key}><span>{action}</span><kbd>{key}</kbd></div>)}</motion.div></motion.div>
}

function App() {
  const [slide, setSlide] = useState(0)
  const [helpOpen, setHelpOpen] = useState(false)
  const [isFullscreen, setIsFullscreen] = useState(false)
  const go = (target: number) => setSlide(Math.max(0, Math.min(totalSlides - 1, target)))

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement
      const isTyping = ['INPUT', 'TEXTAREA', 'SELECT'].includes(target.tagName) || target.isContentEditable
      if (event.key === 'Escape') {
        event.preventDefault()
        event.stopPropagation()
        setHelpOpen(false)
        window.setTimeout(() => {
          if (document.fullscreenElement) void document.exitFullscreen()
        }, 25)
        return
      }
      if (isTyping) return
      if (event.key === 'ArrowRight' || event.key === ' ') { event.preventDefault(); go(slide + 1) }
      else if (event.key === 'ArrowLeft') go(slide - 1)
      else if (event.key === 'Home') go(0)
      else if (event.key === 'End') go(totalSlides - 1)
      else if (event.key.toLowerCase() === 'f') {
        if (document.fullscreenElement) void document.exitFullscreen()
        else void document.documentElement.requestFullscreen()
      }
      else if (event.key === '?') setHelpOpen(true)
    }
    const onFullscreen = () => setIsFullscreen(Boolean(document.fullscreenElement))
    window.addEventListener('keydown', onKeyDown, true)
    document.addEventListener('fullscreenchange', onFullscreen)
    return () => { window.removeEventListener('keydown', onKeyDown, true); document.removeEventListener('fullscreenchange', onFullscreen) }
  }, [slide])

  return <main className="presentation-shell"><div className="ambient-grid"/><div className="topbar"><div className="wordmark"><span>◈</span> FIELDNOTES <i> / </i> FRONTEND</div><div className="topbar-center"><span className="session-dot"/> COLOR SYSTEMS <span className="topbar-divider">·</span> 18 MIN</div><button className="icon-button help-button" aria-label="Keyboard shortcuts" onClick={() => setHelpOpen(true)}><CircleHelp size={17}/><span>Shortcuts</span><kbd>?</kbd></button></div><section className="stage" aria-label={`Slide ${slide + 1}: ${slideTitles[slide]}`}><motion.article key={slide} className={`slide slide-${slide}`} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .24, ease: 'easeOut' }}><SlideContent index={slide}/></motion.article></section><footer className="navigation"><div className="nav-meta"><span className="nav-section">FIELDNOTES <b>04</b></span><span className="nav-title">{slideTitles[slide]}</span></div><div className="nav-controls"><button className="nav-button" onClick={() => go(slide - 1)} disabled={slide === 0} aria-label="Previous slide"><ArrowLeft size={16}/><span>Previous</span></button><div className="slide-count"><b>{String(slide + 1).padStart(2, '0')}</b><span>/</span>{String(totalSlides).padStart(2, '0')}</div><button className="nav-button next-button" onClick={() => go(slide + 1)} disabled={slide === totalSlides - 1} aria-label="Next slide"><span>Next</span><ArrowRight size={16}/></button></div><button className="icon-button fullscreen-button" aria-label={isFullscreen ? 'Exit fullscreen' : 'Enter fullscreen'} onClick={() => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen()}>{isFullscreen ? <Focus size={17}/> : <Expand size={17}/>}</button><div className="progress-track"><motion.div className="progress-fill" animate={{ width: `${((slide + 1) / totalSlides) * 100}%` }} transition={{ duration: .25 }}/></div></footer><AnimatePresence>{helpOpen && <KeyboardHelp onClose={() => setHelpOpen(false)}/>}</AnimatePresence></main>
}

export default App